export const USER_REPOSITORY_MONGO = Symbol('USER_REPOSITORY_MONGO');
export const USER_REPOSITORY_SQL = Symbol('USER_REPOSITORY_SQL');
export const PLANNER_REPOSITORY_SQL = Symbol('PLANNER_REPOSITORY_SQL');

export const AUTH_REPOSITORY_MONGO = Symbol('AUTH_REPOSITORY_MONGO');
